name: EP-XPcheckin
main: ep.xp.checkin.DailyRandomXP
version: 1.4
api-version: 1.18
authors: [system_mini, EndlessPixel]
description: 无尽像素每日随机经验签到插件
commands:
  checkin:
    description: 每日随机经验签到
    usage: /checkin
    permission: ep.checkin
permissions:
  ep.checkin:
    description: 签到权限
    default: true